(ns me.raynes.fs
  "File system utilities in Clojure"
  {:lang :core.typed
   ;:core.typed {:features 
   ;             #{:runtime-infer}}
   }
  (:refer-clojure :exclude [name parents])
  (:require [clojure.zip :as zip]
            [clojure.java.io :as io]
            [clojure.string :as string]
            [clojure.java.shell :as sh]
            [clojure.core.typed :as t]
            [clojure.spec :as s]
            [clojure.spec.test :as stest])
  (:import [java.io File FilenameFilter]))

;; Start: Generated by clojure.core.typed - DO NOT EDIT
(declare
  AsFileAsUrlMap
  DocImplsMethodBuildersMap
  LPnodesPpathMap
  alias__17025
  alias__17433)
(t/defalias AsFileAsUrlMap '{:as-file t/Any, :as-url t/Any})
(t/defalias
  DocImplsMethodBuildersMap
  '{:doc t/Str,
    :impls (t/Map (t/U nil Class) AsFileAsUrlMap),
    :method-builders (t/Map clojure.lang.Var AnyFunction),
    :method-map AsFileAsUrlMap,
    :on t/Sym,
    :on-interface Class,
    :sigs AsFileAsUrlMap,
    :var clojure.lang.Var})
(t/defalias
  LPnodesPpathMap
  '{:l (t/Vec File),
    :pnodes (t/Vec File),
    :ppath (t/U nil alias__17433 alias__17025),
    :r (t/U nil (t/Coll File))})
(t/defalias alias__17025 (t/U nil LPnodesPpathMap))
(t/defalias alias__17433 (t/U nil LPnodesPpathMap))
(t/ann clojure.java.io/Coercions DocImplsMethodBuildersMap)
(t/ann clojure.java.io/copy [File File :-> nil])
(t/ann
  clojure.java.io/file
  [(t/U t/Str File sun.nio.fs.UnixPath) 
   (t/U t/Str File sun.nio.fs.UnixPath) * :-> File])
(t/ann clojure.zip/end? ['[File t/Any] :-> Boolean])
(t/ann clojure.zip/next ['[File alias__17433] :-> '[File t/Any]])
(t/ann clojure.zip/node ['[File alias__17025] :-> File])
(t/ann
  clojure.zip/zipper
  [[File :-> Boolean] [File :-> (Array File)] nil File :-> '[File nil]])
(t/ann *cwd* File)
(t/ann absolute [t/Str :-> File])
(t/ann absolute? [t/Str :-> Boolean])
(t/ann as-path [(t/U t/Str File) :-> sun.nio.fs.UnixPath])
(t/ann assert-exists [(t/U t/Str File) :-> nil])
(t/ann
  base-name
  (t/IFn
    [(t/U t/Str File) :-> t/Str]
    [t/Str (t/U t/Str Boolean) :-> t/Str]))
(t/ann char-to-int [Character :-> t/Int])
(t/ann chdir [t/Str :-> File])
(t/ann child-of? [t/Str t/Str :-> (t/U nil File)])
(t/ann chmod [t/Str (t/U t/Str File) :-> (t/U t/Str File)])
(t/ann chmod-octal [t/Str (t/U t/Str File) :-> (t/U t/Str File)])
(t/ann chmod-octal-digit [File t/Int Boolean :-> Boolean])
(t/ann copy [File File :-> File])
(t/ann copy+ [File File :-> File])
(t/ann copy-dir [File File :-> (t/U nil File)])
(t/ann copy-dir-into [File File :-> (t/U nil File)])
(t/ann create [File :-> Boolean])
(t/ann delete [(t/U t/Str File) :-> Boolean])
(t/ann
  delete-dir
  [(t/U t/Str File) :-> Boolean])
(t/ann
  directory?
  [(t/U t/Str File) :-> Boolean])
(t/ann ^:no-check exec AnyFunction) ;; unused
(t/ann executable? [(t/U t/Str File) :-> Boolean])
(t/ann exists? [(t/U t/Str File) :-> Boolean])
(t/ann expand-home [t/Str :-> File])
(t/ann extension [t/Str :-> (t/U nil t/Str)])
(t/ann ^:no-check f-children [File :-> (Array File)]) ;; arrays broken in core.typed
(t/ann f-dir? [File :-> Boolean])
(t/ann
  file
  [(t/U t/Str File sun.nio.fs.UnixPath)
   (t/U t/Str File sun.nio.fs.UnixPath) * :-> (t/U nil File)])
(t/ann file? [(t/U t/Str File) :-> Boolean])
(t/ann
  ^:no-check ;; unannotated re-matches
  find-files
  [t/Str java.util.regex.Pattern :-> (t/Coll File)])
(t/ann ^:no-check find-files* [t/Str [File :-> nil] :-> (t/Coll File)]) ;; unannotated file-seq
(t/ann ^:no-check glob AnyFunction) ;; unusued
(t/ann ^:no-check glob->regex AnyFunction) ;; unused
(t/ann hidden? [File :-> Boolean])
(t/ann home (t/IFn [t/Str :-> File] [:-> File]))
(t/ann
  iterate-dir
  [File :-> (t/Coll '[File (t/Set t/Str) (t/Set t/Str)])])
(t/ann ^:no-check iterate-dir* [File :-> (t/Coll File)]) ;;uses zipper in def
(t/ann ^:no-check iterzip t/Any) ;; zipper function
(t/ann link [File File :-> File])
(t/ann link? [File :-> Boolean])
(t/ann list-dir [(t/U t/Str File) :-> (t/Coll File)])
(t/ann mkdir [File :-> Boolean])
(t/ann mkdirs [File :-> Boolean])
(t/ann mod-time [File :-> t/Int])
(t/ann
  move
  (t/IFn
    [File
     File
     java.nio.file.StandardCopyOption
     :->
     sun.nio.fs.UnixPath]
    [File File :-> sun.nio.fs.UnixPath]))
(t/ann name [t/Str :-> t/Str])
(t/ann normalized [t/Str :-> File])
(t/ann ns-path [t/Sym :-> File])
(t/ann parent [File :-> (t/U nil File)])
(t/ann parents [(t/U t/Str File) :-> (t/U nil (t/Coll File))])
(t/ann path-ns [t/Str :-> t/Sym])
(t/ann read-sym-link [File :-> File])
(t/ann readable? [(t/U t/Str File) :-> Boolean])
(t/ann rename [(t/U t/Str File) t/Str :-> Boolean])
(t/ann size [File :-> t/Int])
(t/ann split [(t/U t/Str File) :-> (t/Coll t/Str)])
(t/ann split-ext [t/Str :-> '[t/Str (t/U nil t/Str)]])
(t/ann sym-link [File (t/U t/Str File) :-> File])
(t/ann temp-create [t/Str t/Str t/Int [File :-> Boolean] :-> (t/U nil File)])
(t/ann temp-dir (t/IFn [t/Str :-> (t/U nil File)] 
                       [t/Str t/Str :-> (t/U nil File)]
                       [t/Str t/Str t/Int :-> (t/U nil File)]))
(t/ann temp-file (t/IFn [t/Str :-> (t/U nil File)] 
                        [t/Str t/Str :-> (t/U nil File)]
                        [t/Str t/Str t/Int :-> (t/U nil File)]))
(t/ann temp-name [t/Str t/Str :-> t/Str])
(t/ann tmpdir [:-> t/Str])
(t/ann touch (t/IFn [File (t/U nil t/Int) :-> File] [File :-> File]))
(t/ann unix-root (t/U nil t/Str))
(t/ann
  ^:no-check ;; too hard
  walk
  t/Any)
(t/ann walk-map-fn [File :-> '[File (t/Set t/Str) (t/Set t/Str)]])
(t/ann writeable? [(t/U t/Str File) :-> Boolean])
;; End: Generated by clojure.core.typed - DO NOT EDIT

(defmacro assert-file [f]
  `(let [f# ~f]
     (assert (instance? File f#))
     f#))

;; Once you've started a JVM, that JVM's working directory is set in stone
;; and cannot be changed. This library will provide a way to simulate a
;; working directory change. `cwd` is considered to be the current working
;; directory for functions in this library. Unfortunately, this will only
;; apply to functions inside this library since we can't change the JVM's
;; actual working directory.
(def ^{:doc "Current working directory. This cannot be changed in the JVM.
             Changing this will only change the working directory for functions
             in this library."
       :dynamic true}
  *cwd* (assert-file (.getCanonicalFile (io/file "."))))

(let [homedir (io/file (t/cast String (System/getProperty "user.home")))
      usersdir (.getParent homedir)]
  (defn home
    "With no arguments, returns the current value of the `user.home` system
     property. If a `user` is passed, returns that user's home directory. It
     is naively assumed to be a directory with the same name as the `user`
     located relative to the parent of the current value of `user.home`."
    ([] homedir)
    ([user] (if (empty? user) homedir (io/file (t/cast String usersdir) user)))))

(defn expand-home
  "If `path` begins with a tilde (`~`), expand the tilde to the value
  of the `user.home` system property. If the `path` begins with a
  tilde immediately followed by some characters, they are assumed to
  be a username. This is expanded to the path to that user's home
  directory. This is (naively) assumed to be a directory with the same
  name as the user relative to the parent of the current value of
  `user.home`."
  [path]
  (let [path (str path)]
    (if (.startsWith path "~")
      (let [sep (t/cast t/Int (.indexOf path (t/cast String File/separator)))]
        (if (neg? sep)
          (home (subs path 1))
          (io/file (home (subs path 1 sep)) (subs path (inc sep)))))
      (io/file path))))

;; Library functions will call this function on paths/files so that
;; we get the cwd effect on them.
(defn ^File file
  "If `path` is a period, replaces it with cwd and creates a new File object
   out of it and `paths`. Or, if the resulting File object does not constitute
   an absolute path, makes it absolutely by creating a new File object out of
   the `paths` and cwd."
  [path & paths]
  (when-let [path (t/cast
                    (t/U nil File)
                    (t/tc-ignore
                      (apply
                        io/file (if (= path ".")
                                  *cwd*
                                  path)
                        paths)))]
    (if (.isAbsolute ^File path)
      path
      (io/file *cwd* path))))

(defn list-dir
  "List files and directories under `path`."
  [path]
  (seq (.listFiles (assert-file (file path)))))

(defmacro ^:private predicate [s path]
  `(if-let [p# ~path]
     (. p# ~s)
     false))

(defn absolute?
  "Return true if `path` is absolute."
  [path]
  (predicate isAbsolute (io/file path)))

(defn executable?
  "Return true if `path` is executable."
  [path]
  (predicate canExecute (file path)))

(defn readable?
  "Return true if `path` is readable."
  [path]
  (predicate canRead (file path)))

(defn writeable?
  "Return true if `path` is writeable."
  [path]
  (predicate canWrite (file path)))

(defn delete
  "Delete `path`."
  [path]
  (predicate delete (file path)))

(defn exists?
  "Return true if `path` exists."
  [path]
  (predicate exists (file path)))

(defn absolute
  "Return absolute file."
  [path]
  {:post [(instance? File %)]}
  (.getAbsoluteFile (assert-file (file path))))

(defn normalized
  "Return normalized (canonical) file."
  [path]
  {:post [(instance? File %)]}
  (.getCanonicalFile (assert-file (file path))))

(defn ^String base-name
  "Return the base name (final segment/file part) of a `path`.

   If optional `trim-ext` is a string and the `path` ends with that
   string, it is trimmed.

   If `trim-ext` is true, any extension is trimmed."
  ([path] 
   {:post [(string? %)]}
   (.getName (assert-file (file path))))
  ([path trim-ext]
     (let [base (.getName (assert-file (file path)))]
       (assert (string? base))
       (cond (string? trim-ext) (if (.endsWith base trim-ext)
                                  (subs base 0 (- (count base) (count trim-ext)))
                                  base)
             trim-ext (let [dot (.lastIndexOf base ".")]
                        (if (pos? dot) (subs base 0 dot) base))
             :else base))))

(defn directory?
  "Return true if `path` is a directory."
  [path]
  (predicate isDirectory (file path)))

(defn file?
  "Return true if `path` is a file."
  [path]
  (predicate isFile (file path)))

(defn ^Boolean hidden?
  "Return true if `path` is hidden."
  [path]
  (predicate isHidden (file path)))

(defn delete-dir
  "Delete a directory tree."
  [root]
  (when (directory? root)
    (t/doseq [path :- File (.listFiles (assert-file (file root)))]
      (delete-dir path)))
  (delete root))

(defmacro ^:private include-java-7-fns []
  (when (try (import '[java.nio.file Files Path LinkOption CopyOption]
                     '[java.nio.file.attribute FileAttribute])
             (catch Exception _ nil))

    '(do
      (extend-protocol io/Coercions
       Path
       (as-file [this] (.toFile this))
       (as-url [this] (.. this (toFile) (toURL))))

      (defn- ^Path as-path
        "Convert `path` to a `java.nio.file.Path`.
       Requires Java version 7 or greater."
        [path]
        (.toPath (file path)))

      (defn ^Boolean link?
        "Return true if `path` is a link.
       Requires Java version 7 or greater."
        [path]
        (Files/isSymbolicLink (as-path path)))

      (defn ^File link
        "Create a \"hard\" link from path to target.
       Requires Java version 7 or greater.  The arguments
       are in the opposite order from the link(2) system
       call."
        [new-file existing-file]
        (file (Files/createLink (as-path new-file) (as-path existing-file))))

      (defn ^File sym-link
        "Create a \"soft\" link from `path` to `target`.
       Requires Java version 7 or greater."
        [path target]
        (file (Files/createSymbolicLink
               (as-path path)
               (as-path target)
               (make-array FileAttribute 0))))

       (defn ^File read-sym-link
         "Return the target of a 'soft' link.
          Requires Java version 7 or greater."
         [path]
         (file (Files/readSymbolicLink (as-path path))))

      ;; Rewrite directory? and delete-dir to include LinkOptions.
      (defn directory?
        "Return true if `path` is a directory, false otherwise.
        Optional
        [link-options](http://docs.oracle.com/javase/7/docs/api/java/nio/file/LinkOption.html)
        may be provided to determine whether or not to follow symbolic
        links."
        [path & link-options]
        (Files/isDirectory (as-path path)
                           (into-array LinkOption link-options)))

      (defn delete-dir
        "Delete a directory tree. Optional
       [link-options](http://docs.oracle.com/javase/7/docs/api/java/nio/file/LinkOption.html)
       may be provided to determine whether or not to follow symbolic
       links."
        [root & link-options]
        (when (apply directory? root link-options)
          (doseq [path (.listFiles (file root))]
            (apply delete-dir path link-options)))
        (delete root))

      (defn move
        "Move or rename a file to a target file. Requires Java version 7 or greater. Optional
         [copy-options](http://docs.oracle.com/javase/7/docs/api/java/nio/file/CopyOption.html)
         may be provided."
        [source target & copy-options]
        (Files/move (as-path source) (as-path target) (into-array CopyOption copy-options))))))

(t/tc-ignore ;; TODO java.nio functions redefine old def's
(include-java-7-fns)
)

(defn split-ext
  "Returns a vector of `[name extension]`."
  [path]
  (let [base (base-name path)
        i (.lastIndexOf base ".")]
    (if (pos? i)
      [(subs base 0 i) (subs base i)]
      [base nil])))

(defn extension
  "Return the extension part of a file."
  [path] (last (split-ext path)))

(defn name
  "Return the name part of a file."
  [path] (first (split-ext path)))

(defn parent
  "Return the parent path."
  [path]
  (.getParentFile (assert-file (file path))))

(defn mod-time
  "Return file modification time."
  [path]
  (.lastModified (assert-file (file path))))

(defn size
  "Return size (in bytes) of file."
  [path]
  (.length (assert-file (file path))))

(defn mkdir
  "Create a directory."
  [path]
  (.mkdir (assert-file (file path))))

(defn mkdirs
  "Make directory tree."
  [path]
  (.mkdirs (assert-file (file path))))

(def ^{:doc "The root of a unix system is `/`, `nil` on Windows"}
  unix-root (when (= File/separator "/") File/separator))

(defn split
  "Split `path` to components."
  [path]
  (let [pathstr (str path)
        jregx (str "\\Q" File/separator "\\E")
        unix-root unix-root]
    (cond (= pathstr unix-root) (list (t/cast String unix-root))
          (and unix-root (.startsWith pathstr unix-root))
          ;; unix absolute path
            (cons unix-root (seq (.split (subs pathstr 1) jregx)))
          :else (seq (.split pathstr jregx)))))

(defn rename
  "Rename `old-path` to `new-path`. Only works on files."
  [old-path new-path]
  (.renameTo (assert-file (file old-path)) (assert-file (file new-path))))

(defn create
  "Create a new file."
  [^File f]
  (.createNewFile f))

(defn- assert-exists [path]
  (when-not (exists? path)
    (throw (IllegalArgumentException. (str path " not found")))))

(defn copy
  "Copy a file from `from` to `to`. Return `to`."
  [from to]
  (assert-exists from)
  (io/copy (assert-file (file from)) (assert-file (file to)))
  to)

(defn tmpdir
  "The temporary file directory looked up via the `java.io.tmpdir`
   system property. Does not create a temporary directory."
  []
  {:post [(string? %)]}
  (System/getProperty "java.io.tmpdir"))

(defn temp-name
  "Create a temporary file name like what is created for [[temp-file]]
   and [[temp-dir]]."
  ([prefix] (temp-name prefix ""))
  ([prefix suffix]
     (format "%s%s-%s%s" prefix (System/currentTimeMillis)
             (long (rand 0x100000000)) suffix)))

(defn- temp-create
  "Create a temporary file or dir, trying n times before giving up."
  [prefix suffix tries f]
  (let [tmp (file (tmpdir) (temp-name prefix suffix))]
    (assert tmp)
    (when (pos? tries)
      (if (f tmp)
        tmp
        (recur prefix suffix (dec tries) f)))))

(defn temp-file
  "Create a temporary file. Returns nil if file could not be created
   even after n tries (default 10)."
  ([prefix]              (temp-file prefix "" 10))
  ([prefix suffix]       (temp-file prefix suffix 10))
  ([prefix suffix tries] (temp-create prefix suffix tries create)))

(defn temp-dir
  "Create a temporary directory. Returns nil if dir could not be created
   even after n tries (default 10)."
  ([prefix]              (temp-dir prefix "" 10))
  ([prefix suffix]       (temp-dir prefix suffix 10))
  ([prefix suffix tries] (temp-create prefix suffix tries mkdirs)))

; Taken from https://github.com/jkk/clj-glob. (thanks Justin!)
(defn- glob->regex
  "Takes a glob-format string and returns a regex."
  [s]
  (loop [stream s
         re ""
         curly-depth 0]
    (let [[c j] stream]
        (cond
         (nil? c) (re-pattern
                    ; We add ^ and $ since we check only for file names
                    (str "^" (if (= \. (first s)) "" "(?=[^\\.])") re "$"))
         (= c \\) (recur (nnext stream) (str re c c) curly-depth)
         (= c \/) (recur (next stream) (str re (if (= \. j) c "/(?=[^\\.])"))
                         curly-depth)
         (= c \*) (recur (next stream) (str re "[^/]*") curly-depth)
         (= c \?) (recur (next stream) (str re "[^/]") curly-depth)
         (= c \{) (recur (next stream) (str re \() (inc curly-depth))
         (= c \}) (recur (next stream) (str re \)) (dec curly-depth))
         (and (= c \,) (< 0 curly-depth)) (recur (next stream) (str re \|)
                                                 curly-depth)
         (#{\. \( \) \| \+ \^ \$ \@ \%} c) (recur (next stream) (str re \\ c)
                                                  curly-depth)
         :else (recur (next stream) (str re c) curly-depth)))))

(defn glob
  "Returns files matching glob pattern."
  ([pattern]
     (let [parts (split pattern)
           root (apply file (if (= (count parts) 1) ["."] (butlast parts)))]
       (glob root (last parts))))
  ([^File root pattern]
     (let [regex (glob->regex pattern)]
       (seq (.listFiles
             root
             (reify FilenameFilter
               (accept [_ _ filename]
                 (boolean (re-find regex filename)))))))))

(defn- iterzip
  "Iterate over a zip, returns a sequence of the nodes with a nil suffix"
  [z]
  (when-not (zip/end? z)
    (cons (zip/node z) (lazy-seq (iterzip (zip/next z))))))

(defn- f-dir? [^File f]
  (when f (.isDirectory f)))

(defn- f-children [^File f]
  (.listFiles f))

(defn- iterate-dir* [path]
  (let [root (file path)
        nodes (butlast (iterzip (zip/zipper f-dir? f-children nil root)))]
    (filter f-dir? nodes)))

(defn- walk-map-fn [root]
  (let [kids (f-children root)
        dirs (set (map base-name (filter f-dir? kids)))
        files (set (map base-name (filter (complement f-dir?) kids)))]
    [root dirs files]))

(defn iterate-dir
  "Return a sequence `[root dirs files]`, starting from `path` in depth-first order"
  [path]
  (map walk-map-fn (iterate-dir* path)))

(defn walk
  "Lazily walk depth-first over the directory structure starting at
  `path` calling `func` with three arguments `[root dirs files]`.
  Returns a sequence of the results."
  [func path]
  (map #(apply func %) (iterate-dir path)))

(defn touch
  "Set file modification time (default to now). Returns `path`."
  ([path] (touch path nil))
  ([path time]
  (let [f (file path)]
    (assert f)
    (when-not (create f)
      (.setLastModified f (long (or time (System/currentTimeMillis)))))
    f)))

(defn- char-to-int
  [c]
  (- (int c) 48))

(defn- chmod-octal-digit
  [f i user?]
  (if (> i 7)
    (throw (IllegalArgumentException. "Bad mode"))
    (do (.setReadable f (pos? (bit-and i 4)) user?)
        (.setWritable f (pos? (bit-and i 2)) user?)
        (.setExecutable f (pos? (bit-and i 1)) user?))))

(defn- chmod-octal
  [mode path]
  (let [[user group world] (map char-to-int mode)
        _ (assert user)
        _ (assert group)
        _ (assert world)
        f (file path)
        _ (assert f)]
    (if (not= group world)
      (throw (IllegalArgumentException.
              "Bad mode. Group permissions must be equal to world permissions"))
      (do (chmod-octal-digit f world false)
          (chmod-octal-digit f user true)
          path))))

(defn chmod
  "Change file permissions. Returns path.

  `mode` can be a permissions string in octal or symbolic format.
  Symbolic: any combination of `r` (readable) `w` (writable) and
  `x` (executable). It should be prefixed with `+` to set or `-` to
  unset. And optional prefix of `u` causes the permissions to be set
  for the owner only.
  Octal: a string of three octal digits representing user, group, and
  world permissions. The three bits of each digit signify read, write,
  and execute permissions (in order of significance). Note that group
  and world permissions must be equal.

  Examples:

  ```
  (chmod \"+x\" \"/tmp/foo\") ; Sets executable for everyone
  (chmod \"u-wx\" \"/tmp/foo\") ; Unsets owner write and executable
  ```"
  [mode path]
  (assert-exists path)
  (if (t/tc-ignore (re-matches #"^\d{3}$" mode))
    (chmod-octal mode path)
    (let [[_ u op permissions] (re-find #"^(u?)([+-])([rwx]{1,3})$" mode)]
      (assert (or (nil? u) (string? u)))
      (assert (or (nil? permissions) (string? permissions)))
      (when (nil? op) (throw (IllegalArgumentException. "Bad mode")))
      (let [perm-set (set permissions)
            f (file path)
            _ (assert f)
            flag (= op "+")
            user (not (empty? u))]
        (when (perm-set \r) (.setReadable f flag user))
        (when (perm-set \w) (.setWritable f flag user))
        (when (perm-set \x) (.setExecutable f flag user)))
      path)))

(defn copy+
  "Copy `src` to `dest`, create directories if needed."
  [src dest]
  (mkdirs (assert-file (parent dest)))
  (copy src dest))

(defn copy-dir
  "Copy a directory from `from` to `to`. If `to` already exists, copy the directory
   to a directory with the same name as `from` within the `to` directory."
  [from to]
  (when (exists? from)
    (if (file? to)
      (throw (IllegalArgumentException. (str to " is a file")))
      (let [from (file from)
            _ (assert from)
            to (if (exists? to)
                 (file to (base-name from))
                 (file to))
            _ (assert to)
            trim-size (-> from str count inc)
            dest #(file to (subs (str %) trim-size))]
        (mkdirs to)
        (let [walk-fn (t/ann-form
                        (fn [root dirs files]
                          (t/doseq [dir :- t/Str dirs]
                            (when-not (directory? dir)
                              (-> root (file dir) dest assert-file mkdirs)))
                          (t/doseq [f :- t/Str, files]
                            (copy+ (assert-file (file root f)) (assert-file (dest (file root f))))))
                        [File (t/Set t/Str) (t/Set t/Str) :-> nil])]
          (t/tc-ignore ;; hard to type check
            (dorun
              (walk walk-fn from))))
        to))))

(defn copy-dir-into
  "Copy directory into another directory if destination already exists."
  [from to]
  (if-not (exists? to)
    (copy-dir from to)
    (t/doseq [file :- File, (list-dir from)]
      (if (directory? file)
        (copy-dir file to)
        (copy file (io/file to (base-name file)))))))

(defn parents
  "Get all the parent directories of a path."
  [f]
  (when-let [parent (parent (assert-file (file f)))]
    (cons parent (lazy-seq (parents parent)))))

(defn child-of?
  "Takes two paths and checks to see if the first path is a parent
   of the second."
  [p c] (some #{(file p)} (parents c)))

(defn ns-path
  "Takes a namespace symbol and creates a path to it. Replaces hyphens with
   underscores. Assumes the path should be relative to cwd."
  [n]
  {:post [(instance? File %)]}
  (file
   (str (let [s (. (str n) (replace \- \_))
              _ (assert s)
              s (. s (replace \. \/))]
          s)
        ".clj")))

(defn path-ns
  "Takes a `path` to a Clojure file and constructs a namespace symbol
   out of the path."
  [path]
  (symbol
    (let [s (.replaceAll (str path) "\\.clj" "")
          _ (assert s)
          s (. s (replace \_ \-))
          _ (assert s)
          s (. s (replace \/ \.))
          _ (assert s)]
      s)))

(defn find-files*
  "Find files in `path` by `pred`."
  [path pred]
  (filter pred (-> path file file-seq)))

(defn find-files
  "Find files matching given `pattern`."
  [path pattern]
  (find-files* path #(re-matches pattern (.getName ^File %))))

(defn exec
  "Execute a shell command in the current directory"
  [& body]
  (sh/with-sh-dir *cwd* (apply sh/sh body)))

(defmacro with-cwd
  "Execute `body` with a changed working directory."
  [cwd & body]
  `(binding [*cwd* (file ~cwd)]
     ~@body))

(defmacro with-mutable-cwd
  "Execute the `body` in a binding with `*cwd*` bound to `*cwd*`.
   This allows you to change `*cwd*` with `set!`."
  [& body]
  `(binding [*cwd* *cwd*]
     ~@body))

(defn chdir
  "set!s the value of `*cwd*` to `path`. Only works inside of
   [[with-mutable-cwd]]"
  [path]
  (set! *cwd* (assert-file (file path))))
